# Asociation Rule

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [3]:
data=pd.read_csv('D:\Praktikum\dataminingc_week6.csv')
data

,TV,Speaker,DVD,Kulkas,Antena,Kipas Angin,AC,Dispenser,Setrika,Mesin Cuci,Mixer,Rice Cooker,Kode
0,0,1,0,1,1,1,1,0,0,1,1,0,PP1
1,1,0,1,0,0,0,0,1,0,0,1,1,PP2
2,1,0,1,0,1,1,0,0,0,1,0,1,PP3
3,1,1,1,0,0,0,0,1,0,0,1,1,PP4
4,1,0,1,1,1,0,0,0,0,0,1,0,PP5
5,1,0,0,0,1,0,1,0,0,1,0,0,PP6
6,1,1,1,0,0,0,1,1,0,0,0,0,PP7
7,1,1,1,0,1,1,0,0,0,0,0,0,PP8
8,0,1,0,1,0,1,1,0,0,1,0,0,PP9
9,1,0,1,1,0,0,0,0,0,1,0,1,PP10
10,1,0,0,0,1,0,0,0,0,1,0,1,PP11
11,1,1,1,1,1,1,0,0,0,0,0,0,PP12

In [4]:
data=data.drop('Kode',axis=1)
data.head()

,TV,Speaker,DVD,Kulkas,Antena,Kipas Angin,AC,Dispenser,Setrika,Mesin Cuci,Mixer,Rice Cooker
0,0,1,0,1,1,1,1,0,0,1,1,0
1,1,0,1,0,0,0,0,1,0,0,1,1
2,1,0,1,0,1,1,0,0,0,1,0,1
3,1,1,1,0,0,0,0,1,0,0,1,1
4,1,0,1,1,1,0,0,0,0,0,1,0

In [5]:
frequent_itemsets = apriori(data, min_support=0.3, use_colnames=True)
frequent_itemsets

     support                itemsets
0   0.833333                    (TV)
1   0.500000               (Speaker)
2   0.666667                   (DVD)
3   0.416667                (Kulkas)
4   0.583333                (Antena)
5   0.416667           (Kipas Angin)
6   0.333333                    (AC)
7   0.500000            (Mesin Cuci)
8   0.333333                 (Mixer)
9   0.416667           (Rice Cooker)
10  0.333333           (Speaker, TV)
11  0.666667               (DVD, TV)
12  0.500000            (Antena, TV)
13  0.333333        (Mesin Cuci, TV)
14  0.416667       (Rice Cooker, TV)
15  0.333333          (Speaker, DVD)
16  0.333333  (Speaker, Kipas Angin)
17  0.333333           (DVD, Antena)
18  0.333333      (DVD, Rice Cooker)
19  0.333333   (Antena, Kipas Angin)
20  0.333333    (Mesin Cuci, Antena)
21  0.333333      (Speaker, TV, DVD)
22  0.333333       (DVD, Antena, TV)
23  0.333333  (DVD, Rice Cooker, TV)

In [6]:
rules = association_rules(frequent_itemsets, metric="confidence",min_threshold=0.7)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(DVD),(TV),0.666667,0.833333,0.666667,1.000000,1.200000,0.111111,inf
1,(TV),(DVD),0.833333,0.666667,0.666667,0.800000,1.200000,0.111111,1.666667
2,(Antena),(TV),0.583333,0.833333,0.500000,0.857143,1.028571,0.013889,1.166667
3,(Rice Cooker),(TV),0.416667,0.833333,0.416667,1.000000,1.200000,0.069444,inf
4,(Kipas Angin),(Speaker),0.416667,0.500000,0.333333,0.800000,1.600000,0.125000,2.500000
5,(Rice Cooker),(DVD),0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667
6,(Kipas Angin),(Antena),0.416667,0.583333,0.333333,0.800000,1.371429,0.090278,2.083333
7,"(Speaker, TV)",(DVD),0.333333,0.666667,0.333333,1.000000,1.500000,0.111111,inf
8,"(Speaker, DVD)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
9,"(DVD, Antena)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
10,"(DVD, Rice Cooker)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
11,"(Rice Cooker, TV)",(DVD),0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667
12,(Rice Cooker),"(DVD, TV)",0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667

In [7]:
rules.sort_values(by=['support'],ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(DVD),(TV),0.666667,0.833333,0.666667,1.000000,1.200000,0.111111,inf
1,(TV),(DVD),0.833333,0.666667,0.666667,0.800000,1.200000,0.111111,1.666667
2,(Antena),(TV),0.583333,0.833333,0.500000,0.857143,1.028571,0.013889,1.166667
3,(Rice Cooker),(TV),0.416667,0.833333,0.416667,1.000000,1.200000,0.069444,inf
4,(Kipas Angin),(Speaker),0.416667,0.500000,0.333333,0.800000,1.600000,0.125000,2.500000
5,(Rice Cooker),(DVD),0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667
6,(Kipas Angin),(Antena),0.416667,0.583333,0.333333,0.800000,1.371429,0.090278,2.083333
7,"(Speaker, TV)",(DVD),0.333333,0.666667,0.333333,1.000000,1.500000,0.111111,inf
8,"(Speaker, DVD)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
9,"(DVD, Antena)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
10,"(DVD, Rice Cooker)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
11,"(Rice Cooker, TV)",(DVD),0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667
12,(Rice Cooker),"(DVD, TV)",0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667

In [8]:
rules.sort_values(by=['confidence'],ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(DVD),(TV),0.666667,0.833333,0.666667,1.000000,1.200000,0.111111,inf
3,(Rice Cooker),(TV),0.416667,0.833333,0.416667,1.000000,1.200000,0.069444,inf
7,"(Speaker, TV)",(DVD),0.333333,0.666667,0.333333,1.000000,1.500000,0.111111,inf
8,"(Speaker, DVD)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
9,"(DVD, Antena)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
10,"(DVD, Rice Cooker)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
2,(Antena),(TV),0.583333,0.833333,0.500000,0.857143,1.028571,0.013889,1.166667
1,(TV),(DVD),0.833333,0.666667,0.666667,0.800000,1.200000,0.111111,1.666667
4,(Kipas Angin),(Speaker),0.416667,0.500000,0.333333,0.800000,1.600000,0.125000,2.500000
5,(Rice Cooker),(DVD),0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667
6,(Kipas Angin),(Antena),0.416667,0.583333,0.333333,0.800000,1.371429,0.090278,2.083333
11,"(Rice Cooker, TV)",(DVD),0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667
12,(Rice Cooker),"(DVD, TV)",0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667

In [9]:
rules.sort_values(by=['lift'],ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
4,(Kipas Angin),(Speaker),0.416667,0.500000,0.333333,0.800000,1.600000,0.125000,2.500000
7,"(Speaker, TV)",(DVD),0.333333,0.666667,0.333333,1.000000,1.500000,0.111111,inf
6,(Kipas Angin),(Antena),0.416667,0.583333,0.333333,0.800000,1.371429,0.090278,2.083333
0,(DVD),(TV),0.666667,0.833333,0.666667,1.000000,1.200000,0.111111,inf
1,(TV),(DVD),0.833333,0.666667,0.666667,0.800000,1.200000,0.111111,1.666667
3,(Rice Cooker),(TV),0.416667,0.833333,0.416667,1.000000,1.200000,0.069444,inf
5,(Rice Cooker),(DVD),0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667
8,"(Speaker, DVD)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
9,"(DVD, Antena)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
10,"(DVD, Rice Cooker)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
11,"(Rice Cooker, TV)",(DVD),0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667
12,(Rice Cooker),"(DVD, TV)",0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667
2,(Antena),(TV),0.583333,0.833333,0.500000,0.857143,1.028571,0.013889,1.166667

In [7]:
rules.sort_values(by=['confidence','lift'],ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
7,"(TV, Speaker)",(DVD),0.333333,0.666667,0.333333,1.000000,1.500000,0.111111,inf
1,(DVD),(TV),0.666667,0.833333,0.666667,1.000000,1.200000,0.111111,inf
3,(Rice Cooker),(TV),0.416667,0.833333,0.416667,1.000000,1.200000,0.069444,inf
8,"(DVD, Speaker)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
9,"(Antena, DVD)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
11,"(DVD, Rice Cooker)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
2,(Antena),(TV),0.583333,0.833333,0.500000,0.857143,1.028571,0.013889,1.166667
4,(Kipas Angin),(Speaker),0.416667,0.500000,0.333333,0.800000,1.600000,0.125000,2.500000
6,(Kipas Angin),(Antena),0.416667,0.583333,0.333333,0.800000,1.371429,0.090278,2.083333
0,(TV),(DVD),0.833333,0.666667,0.666667,0.800000,1.200000,0.111111,1.666667
5,(Rice Cooker),(DVD),0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667
10,"(TV, Rice Cooker)",(DVD),0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667
12,(Rice Cooker),"(TV, DVD)",0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667

In [8]:
rules.sort_values(by=['support','confidence','lift'],ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
1,(DVD),(TV),0.666667,0.833333,0.666667,1.000000,1.200000,0.111111,inf
0,(TV),(DVD),0.833333,0.666667,0.666667,0.800000,1.200000,0.111111,1.666667
2,(Antena),(TV),0.583333,0.833333,0.500000,0.857143,1.028571,0.013889,1.166667
3,(Rice Cooker),(TV),0.416667,0.833333,0.416667,1.000000,1.200000,0.069444,inf
7,"(TV, Speaker)",(DVD),0.333333,0.666667,0.333333,1.000000,1.500000,0.111111,inf
8,"(DVD, Speaker)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
9,"(Antena, DVD)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
11,"(DVD, Rice Cooker)",(TV),0.333333,0.833333,0.333333,1.000000,1.200000,0.055556,inf
4,(Kipas Angin),(Speaker),0.416667,0.500000,0.333333,0.800000,1.600000,0.125000,2.500000
6,(Kipas Angin),(Antena),0.416667,0.583333,0.333333,0.800000,1.371429,0.090278,2.083333
5,(Rice Cooker),(DVD),0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667
10,"(TV, Rice Cooker)",(DVD),0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667
12,(Rice Cooker),"(TV, DVD)",0.416667,0.666667,0.333333,0.800000,1.200000,0.055556,1.666667